# Print options

Numpy outputs can be configured through `set_printoptions` function. Here is described with examples some options.

For more information, see the corresponding page in the [official documentation](https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html).

In [1]:
import numpy as np

np.random.seed(1)
arr = np.random.uniform(-10, 10, 20)

## `precision`

Allows you to select the number of characters to be displayed after the decimal separator. By default it's 8.

---

The following cell shows outputs for the different values of the parameter.

In [4]:
print("precision=3")
np.set_printoptions(
    precision=3
)
print(arr)
print("precision=5")
np.set_printoptions(
    precision=5
)
print(arr)

precision=3
[-1.66   4.406 -9.998 -3.953 -7.065 -8.153 -6.275 -3.089 -2.065  0.776
 -1.616  3.704 -5.911  7.562 -9.452  3.409 -1.654  1.174 -7.192 -6.038]
precision=5
[-1.65956  4.40649 -9.99771 -3.95335 -7.06488 -8.15323 -6.2748  -3.08879
 -2.06465  0.77633 -1.61611  3.70439 -5.91096  7.56235 -9.45225  3.40935
 -1.6539   1.1738  -7.19226 -6.03797]


## `threshold`

Allows you to set how many icons will be displayed without hiding any information. The default is 1000.

In [5]:
print("threshold=20; lead to full display of the array")
np.set_printoptions(threshold=20)
print(arr)
print("threshold=19; lead ot display just summary of the array")
np.set_printoptions(threshold=19)
print(arr)

threshold=20; lead to full display of the array
[-1.65956  4.40649 -9.99771 -3.95335 -7.06488 -8.15323 -6.2748  -3.08879
 -2.06465  0.77633 -1.61611  3.70439 -5.91096  7.56235 -9.45225  3.40935
 -1.6539   1.1738  -7.19226 -6.03797]
threshold=19; lead ot display just summary of the array
[-1.65956  4.40649 -9.99771 ...  1.1738  -7.19226 -6.03797]


## `edgeitems`

Defines how many elements are displayed on both sides of `...`. By default it's 3.

In [6]:
np.set_printoptions(
    edgeitems=3,
    threshold=0
)
print("edgeitems=3")
print(arr)
np.set_printoptions(
    edgeitems=5
)
print("edgeitems=5")
print(arr)

edgeitems=3
[-1.65956  4.40649 -9.99771 ...  1.1738  -7.19226 -6.03797]
edgeitems=5
[-1.65956  4.40649 -9.99771 -3.95335 -7.06488 ...  3.40935 -1.6539
  1.1738  -7.19226 -6.03797]


## `linewidth`

How many characters will be displayed on each line, the default is 75. `[` and `\n` are also counted. That's why you always get 3 characters less from the array. The result seems to be approximate, because the specified `linewidth` may not be a multiple of the number of matrix symbols. Moreover, strings are different - minuses, and the value of the `precision` argument will affect the length of strings.

---

The follwing cell sets the parameter under consideration to the 20. And prints the array.

In [15]:
np.set_printoptions(
    linewidth=20,
    threshold=1000,
    precision=1
)
print(arr)

[ -1.7   4.4 -10.
  -4.   -7.1  -8.2
  -6.3  -3.1  -2.1
   0.8  -1.6   3.7
  -5.9   7.6  -9.5
   3.4  -1.7   1.2
  -7.2  -6. ]


Array is printed thinner than the default numpy representation. To be sure that numpy has followed to the specified instructions, the following cell counts the number of symbols for each row.

In [23]:
matr_strs = str(arr).split("\n")
for line in matr_strs:
    print(f"- '{line}' - {len(line)} symbols")

- '[ -1.7   4.4 -10.' - 17 symbols
- '  -4.   -7.1  -8.2' - 18 symbols
- '  -6.3  -3.1  -2.1' - 18 symbols
- '   0.8  -1.6   3.7' - 18 symbols
- '  -5.9   7.6  -9.5' - 18 symbols
- '   3.4  -1.7   1.2' - 18 symbols
- '  -7.2  -6. ]' - 13 symbols


All lines have less than 20 symbols - the only option to fit the array into lines that don't take more than 20 symbols.

## Fixed point notation

Fixed point notation (e.g. exponential notation, scientific notation) is a way of writting numbers like this `1e-4`. By default, numpy will print any array using this type of notation only if $m < 1e-4$ or $M/m > 1e3$, where $m$ minimum value in the array under consideration $M$ maximum value of the array under consideration. You can change the behaviour by using the `supress=True` parameter of the `set_printoptions`, this forces numpy to always use the regular form of the number. 

---

The following cell creates a numpy array where one of the numbers is extremely small, and displays it with different values of the `suppress` parameter.

In [7]:
example_array = np.array([1e-6, 10])

np.set_printoptions(suppress=True)
print(example_array)

np.set_printoptions(suppress=False)
print(example_array)

[ 0.000001 10.      ]
[1.e-06 1.e+01]


The same example, but using a different rule of printing value in the scientific form - ratio of minimum and maximum numbers.

In [10]:
example_array = np.array([1, 1e+5])

np.set_printoptions(suppress=True)
print(example_array)

np.set_printoptions(suppress=False)
print(example_array)

[     1. 100000.]
[1.e+00 1.e+05]


**Note:** Scientific notation doesn't work for the integer datatype. The following cell show examples with the same arrays, but one stored in the integer datatype and the other in the float datatype.

In [11]:
np.set_printoptions(suppress = False)

print("int")
ints_arr = np.array([1, 1001])
print(ints_arr, end = "\n\n\n")

floats_arr = np.array([1.0, 1001])
print("float")
print(floats_arr)

int
[   1 1001]


float
[1.000e+00 1.001e+03]


## `nanstr` 

`nanstr` parameter allows to set what string to use for pringing `NaN` values.

---

The following cell prints an array with `nanstr="No data"`.

In [5]:
np.set_printoptions(nanstr="No data")

nan_arr = np.fromfunction(
    lambda i, j: np.where(
        (i+j)%2, 0, np.nan
    ),
    (4,4)
)

nan_arr

array([[No data,      0., No data,      0.],
       [     0., No data,      0., No data],
       [No data,      0., No data,      0.],
       [     0., No data,      0., No data]])

## `infstr`

The `infstr` parameter allows you to specify how the way infinity is displayed on your numpy arrays.

---

Following code shows how `Custom infinity` line can be used for defining how infinity values have to be displayed in numpy arrays.

In [7]:
np.set_printoptions(infstr="Custom infinity")

nan_arr = np.fromfunction(
    lambda i, j: np.where(
        (i+j)%2, -np.inf, np.inf
    ),
    (4,4)
)

nan_arr

array([[ Custom infinity, -Custom infinity,  Custom infinity,
        -Custom infinity],
       [-Custom infinity,  Custom infinity, -Custom infinity,
         Custom infinity],
       [ Custom infinity, -Custom infinity,  Custom infinity,
        -Custom infinity],
       [-Custom infinity,  Custom infinity, -Custom infinity,
         Custom infinity]])

## `sign`

With sign parameter allows you specify how numpy handles the displaycement of the `+` sign. Generally it can take 3 values " ", "+" and "-":

- In case of "-", nothing is printed.
- In the case "+", each positive number is preceded by a "+".
- In the case " ", each positive number is preceded by a space.  

---

The next cell shows the differences in display for all possible cases.

In [8]:
np.set_printoptions(
    sign='-',
    linewidth=10
)
print(np.array([1.0]))

np.set_printoptions(sign='+')
print(np.array([1.0]))

np.set_printoptions(sign=' ')
print(np.array([1.0]))

[1.]
[+1.]
[ 1.]


**Note:** if you're using `sign='-'`, numpy still may can add some space to the negative numbers just to make the result to look like a matrix.

In [ ]:
arr = np.random.normal(0, 1, [3, 3])

np.set_printoptions(sign='-', linewidth=50)
print(arr)

[[-0.27320818 -1.730814   -0.25073122]
 [ 0.62554647  1.92942427  0.4122529 ]
 [ 0.42870972  0.18284921 -0.80934173]]
[[-0.27320818 -1.730814   -0.25073122]
 [ 0.62554647  1.92942427  0.4122529 ]
 [ 0.42870972  0.18284921 -0.80934173]]


# Formatter

Позволяет для каждого типа определить функцию как элементы этого массива будут преобразованы в функции. Функция ожидает словарь, в котором для каждого типа массива `numpy` может быть указан способ превращения в строку. Более подробно о всех типах можно уздать из [оффициальной документации](#1). Мы же рассмотрим только случаи показавшиеся мне интерестными:

### Базовый случай рассмотрим с использованием типа данных `bool`

In [15]:
bool_exprimental = np.array([True, False])
def bool_formatter(val):
    return "Истинна" if val else "Ложь"

np.set_printoptions(
    formatter={'bool':bool_formatter}
)
print("bool dtype")
print(bool_exprimental)

print("int dtype")
print(arr)

bool dtype
[Истинна Ложь]
int dtype
[-1.65955991  4.40648987 -9.9977125
 -3.95334855 -7.06488218 -8.1532281
 -6.27479577 -3.08878546 -2.06465052
  0.77633468 -1.61610971  3.70439001
 -5.91095501  7.56234873 -9.45224814
  3.4093502  -1.65390395  1.17379657
 -7.19226123 -6.03797022]


Использование пустого словаря переданного `formatter` приведёт к отмене всех установлленых функций форматирования.

In [16]:
np.set_printoptions(formatter={})
print(bool_exprimental)

[ True False]


### Ключ `all` позволит применить этот форматер ко всем типам данных

В следующем примере для ключа `all` применяется функция которая для чисел типа `numpy.float64` вернет `Дробное` а для любого другого числа `Что-то ещё`.

In [17]:
np.set_printoptions(
    formatter = {
        'all' : lambda val: 
        "Дробное" if type(val) == np.float64 else "Что-то ещё"
    }
)

print("float64 примет вид")
print(arr)
print("int64 примет вид")
print(np.array([0, 1, 2, 3]))

float64 примет вид
[Дробное Дробное Дробное Дробное
 Дробное Дробное Дробное Дробное
 Дробное Дробное Дробное Дробное
 Дробное Дробное Дробное Дробное
 Дробное Дробное Дробное Дробное]
int64 примет вид
[Что-то ещё Что-то ещё Что-то ещё
 Что-то ещё]


Интерестно, какой из ключей будет приоритетнее `all` или для некоторого конкретного типа.

In [18]:
np.set_printoptions(
    formatter = {
        'bool' : lambda x: "ключ для bool",
        'all' : lambda x: "ключ для all"
    }
)

bool_array = np.random.choice([True, False], 20)
bool_array

array([ключ для bool, ключ для bool,
       ключ для bool, ключ для bool,
       ключ для bool, ключ для bool,
       ключ для bool, ключ для bool,
       ключ для bool, ключ для bool,
       ключ для bool, ключ для bool,
       ключ для bool, ключ для bool,
       ключ для bool, ключ для bool,
       ключ для bool, ключ для bool,
       ключ для bool, ключ для bool])

Похоже, ключ определнного типа имеет приоритет.

## `floatmode`

Позволяет уточникть повередение преобразования дробных чисел в случае, если `precision` имеет спорное знечение. Вообще все сводится к двум случаям:
- Число не может быть однозначно определено используя столько знаков;
- Для однозначного определения числа слишком много знаков.

В следующем массиве при `precision = 3` представлены оба случая.

In [19]:
np.set_printoptions(precision = 3)

test_arr = np.array(
    [0.4839, 0.7]
)

Далее рассмотрим значения, которые может принимать `floatmode`.

### `fixed`

Означат безприкословное исполнение числа символов указанное, в `precision`. То есть неоднозначно определяемые числа будут округлены а числа с излишним количесвом знаков для однозначного определния будут дополнены `0`.

In [20]:
np.set_printoptions(
    floatmode = 'fixed',
    precision = 3
)

test_arr

array([0.484, 0.700])

### `unique`

Озанчает, что будет использовано ровно столько знаков, сколько требуется для однозначного определения числа. По сути, это эквивалентно полному игнорированию аргумента `precision`.

In [21]:
np.set_printoptions(
    floatmode = 'unique'
)

test_arr

array([0.4839, 0.7   ])

### `maxprec`

Используется не более чем `precision` цифр. То есть, несмотря на неоднозначно определяемые числа используется не более `precision` знаков, а для числа, содеражащего менее `precision` цифр не происходит автодополнения нулями.

In [22]:
np.set_printoptions(floatmode = "maxprec")
test_arr

array([0.484, 0.7  ])

### `maxprec_equal`

Будет обозначать что используется всегда не более `precision` знаков. Но, в случае, если ни для однозначного определния любого из чисел требуется меньше знаков чем `precision` то будет использовано ровно столько занков сколько требуется. При этом все числа имеют одинаковое число выводимых знаков, т.е. вслучае если число ($a$) однозначно определяется меньшим числом знаков нежели число определившие число знаков, то число $a$ при выводе будет дополнено нулями.

In [23]:
np.set_printoptions(floatmode = "maxprec_equal")
print('требуется 4 занка для определения первого числа')
print(test_arr)
print('требуется 2 знака для определения первого числа')
print(np.array([0.55, 0.5]))

требуется 4 занка для определения первого числа
[0.484 0.700]
требуется 2 знака для определения первого числа
[0.55 0.50]


# Legacy

Используется для ограницазции поддержки старого когда. Может быть использован для возврата к версиям:

- `1.13`;
- `1.21`;
- `False` - гворит о том, что не надо использовать `legacy`.

#### `1.13`

Из документации удалось выяснить только что предыдущие версии отличаются заменой знака на пропуск для полижительного числа. В документации упоминаются и прочие особенности отображения для нульмерных массивов, которые до сих поа для меня остаются загадкой.

In [34]:
test_arr = np.array([1.123456789])

np.set_printoptions(legacy = False)
print(test_arr)

np.set_printoptions(legacy = '1.13')
print(test_arr)

[1.123]
[ 1.123]


#### `1.21`

Утвержается об сособенностях в отображении для сложных структурных типов. Но пока о об таких типах мне тоже не известно, потому, пока просто будем иметь эту возможность ввиду.

In [39]:
test_arr = np.array(
    [('Rex', 9, 81.0), ('Fido', 3, 27.0)],
    dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
)

np.set_printoptions(legacy = False)
print(test_arr)

np.set_printoptions(legacy = '1.21')
print(test_arr)

[('Rex', 9, 81.) ('Fido', 3, 27.)]
[('Rex', 9, 81.) ('Fido', 3, 27.)]
