**Тут я собираю сведения о функция `numpy` которымы должен пользоваться или постоянно забываю как**

In [2]:
import numpy as np

# `fromfunciton`

Позволяет создать `numpy.array` используя правило задаваемое через функцию.

In [3]:
np.fromfunction(lambda i, j: i*3 + j, (4,4))

array([[ 0.,  1.,  2.,  3.],
       [ 3.,  4.,  5.,  6.],
       [ 6.,  7.,  8.,  9.],
       [ 9., 10., 11., 12.]])

### `numpy` всегда оперирует массивами

Следует помнить, что `numpy` всегда оперирует массивами. Рассмотрим пример кода из следующей ячейки. Тут предполагается возвращать для четной суммы индексов строковое значение "четная" а для не четной суммы индексов "нечетная".

In [7]:
np.fromfunction(
    lambda i,j:"Четая" if i>j else "Не четная",
    (4,4)
)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Для того, чтобы разобраться почему так происходит, выведем параметы, которые приходят в функцию-правило переданную `fromfunction`.

In [8]:
def test_func(i,j):
    print(i)
    print(j)
    return 0

np.fromfunction(test_func, (4,4))

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


0

Итак, приходят матрицы с индексами по строчкам для аргумента `i` и по столбцам для аргумента `j`.

In [5]:
np.fromfunction(
    lambda i,j: np.where((i+j)%2==0, "четная", "нечетная"),
    (4,4)
)

array([['четная', 'нечетная', 'четная', 'нечетная'],
       ['нечетная', 'четная', 'нечетная', 'четная'],
       ['четная', 'нечетная', 'четная', 'нечетная'],
       ['нечетная', 'четная', 'нечетная', 'четная']], dtype='<U8')